name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://www.audi.co.uk/uk/web/en.html
            https://www.audi.co.uk/uk/web/en/models.html
            https://www.audi.co.uk/uk/web/en/find-and-buy/finance-and-offers.html
            https://www.audi.co.uk/uk/web/en/find-and-buy/finance-and-offers/part-exchange.html
            https://www.audi.co.uk/uk/web/en/owners/servicing.html
            https://www.audi.co.uk/uk/web/en/owners/electric.html
            https://www.audi.co.uk/uk/web/en/electric.html
            https://www.audi.co.uk/uk/web/en/models/a3/a3-sportback.html
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
